name: CMake
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  cmake-build:
    runs-on: ubuntu-22.04
    container:
      image: lunarnatalie/os-build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        id: env
        run: echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure for i686-elf
        working-directory: ${{ github.workspace }}
        run: cmake -B ${{ steps.env.outputs.build-dir }} --preset i686-elf

      - name: Build
        working-directory: ${{ steps.env.outputs.build-dir }}
        run: cmake --build

      - name: Test
        working-directory: ${{ steps.env.outputs.build-dir }}
        run: ctest
