name: CMake
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cmake-build:
    runs-on: ubuntu-22.04
    container:
      image: lunarnatalie/os-build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        id: env
        run: echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure for i686-elf
        working-directory: ${{ github.workspace }}
        run: cmake -B ${{ steps.env.outputs.build-dir }} --preset i686-elf

      - name: Build
        run: cmake --build ${{ steps.env.outputs.build-dir }}

      - name: Test
        run: ctest --test-dir ${{ steps.env.outputs.build-dir }}
