name: CMake
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  cmake-build:
    runs-on: ubuntu-22.04
    container:
      image: lunarnatalie/os-build

    steps:
      - name: Set additional environment variables
        id: env
        shell: bash
        run: >
          echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure for i686-elf
        run: cmake -S ${{ github.workspace }} -B ${{ steps.env.outputs.build-dir }} --preset i686-elf

      - name: Build
        run: cmake --build ${{ steps.env.outputs.build-dir }}

      - name: Test
        working-directory: ${{ steps.env.outputs.build-output-dir }}
        run: ctest
